baseURL = "TBD"
copyright = "Creative Commons Attribution-ShareAlike 3.0 United States."
languageCode = "en-us"
metaDataFormat = "yaml"
title = "Coding Mental"
SectionPagesMenu = "main"

[taxonomies]
    topic = "topics"
    tag = "tags"

[params]
    description = "Coding Mental, a blog by the tech team at MHA-NYC"
    keywords = ""
    shortTitle = "Coding Mental"
