baseURL = "http://compiled.ctl.columbia.edu/"
copyright = "Creative Commons Attribution-ShareAlike 3.0 United States."
googleAnalytics = "UA-51144540-12"
languageCode = "en-us"
metaDataFormat = "yaml"
title = "CompilED: And Often Interpreted"
SectionPagesMenu = "main"

[taxonomies]
    topic = "topics"
    tag = "tags"

[params]
    description = "CompilED is a collection of reflections and comments by the software developers at Columbia's Center for Teaching and Learning (CTL). These views are rooted in our professional and personal experiences developing educational technology. This blog is directed at hackers, programmers, designers, and architects of all flavors, but everyone is welcome."
    keywords = ""
    shortTitle = "CompilED"
